import Link from '@/components/eon/PageLink';
import JourneyNav,{ServiceEnquiry} from '@/components/eon/JourneyNav';
import {pageMetadata} from '@/lib/eon/metadata';
export const metadata=pageMetadata({title:'Office AC Duct Care',description:'AC duct cleaning and optional treatment for offices in Abu Dhabi. Plan access, work areas and building coordination with Eon Coatings.',path:'/services/office-ac-duct-care/'});
const questions=[
 ['Can work be arranged around office hours?','Share your operating hours and preferred access windows. We will confirm availability and whether the work needs to be divided into areas before agreeing a schedule.'],
 ['What should our facilities team provide?','The office location, approximate floor area, AC layout if available, ceiling access details and any building-management requirements help define the scope.'],
 ['Will desks and meeting rooms need to be cleared?','Confirm which work areas will be affected, what equipment or furniture needs moving and how those areas will be protected before the visit.'],
 ['Is sanitisation or coating included with cleaning?','These are separate treatments. Cleaning removes accumulated dust and debris; any sanitisation or mold-resistant coating must be agreed for the system and its condition.'],
 ['What if the AC is shared with other tenants?','Let us know who manages the system. Access and work boundaries should be coordinated with building management before the service is booked.']
];
export default function OfficeAC(){return <main id="main"><JourneyNav current="Office AC care"/>
<section className="service-hero-new"><div><p className="eyebrow">Office &amp; commercial AC care</p><h1>AC duct care for your workplace.</h1><p>Cleaning for ductwork serving workstations, meeting rooms and shared office spaces. Plan the scope around your building, access requirements and working hours.</p><div className="service-actions"><ServiceEnquiry slug="office-ac-duct-care" title="Office AC care"/><Link href="/services/ac-duct-mold-resistant-coating/" className="text-link">Looking after a home or villa? ›</Link></div></div><figure><img src="/images/unique-care/office-air.webp" alt="Ceiling AC and exposed ductwork above office workstations" width="1536" height="1024"/></figure></section>
<section className="section service-guide"><div className="section-title"><div><p className="eyebrow">Before work begins</p><h2>Coordinate the building, not just the vents.</h2></div><p>Help us understand your systems and occupied areas before we propose the work.</p></div><div className="service-guide-grid">{[['System access','Identify ceiling access points, the floors involved and who manages the AC system. Share drawings or system details if available.'],['Workplace planning','Discuss occupied desks, meeting-room use, equipment protection and approved work windows with your facilities team.'],['Agreed scope','Confirm the ductwork to be cleaned, any optional treatments, access arrangements and handover requirements.']].map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className="section service-scenario service-scenario-air"><img src="/images/refreshed/office-working-v3.webp" alt="Technician on a stepladder working at a ceiling vent in an office meeting room; illustrative scene" width="1536" height="1024" loading="lazy"/><div><p className="eyebrow">Commercial interiors</p><h2>From meeting rooms to open-plan offices.</h2><p>Concealed ducts and ceiling vents need access that works with the space below. Discuss the areas affected and how to manage the visit with your office or building team.</p><ul><li>Workstations and shared work areas</li><li>Meeting rooms and reception spaces</li><li>Tenant offices with building-managed systems</li></ul></div></section>
<section className="section service-faq"><div><p className="eyebrow">For office managers</p><h2>Planning your service.</h2><p>Access and coordination matter as much as the treatment itself.</p></div><div className="faq-list">{questions.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
<section className="section service-next"><div><h2>Discuss your office AC requirements.</h2><p>Share the building, areas involved and preferred schedule.</p></div><ServiceEnquiry slug="office-ac-duct-care" title="Office AC care"/></section></main>}
