import Link from 'next/link';
import DuctStory from '@/components/eon/DuctStory';
import {Consultation,ServiceDirectory,Faqs,FeaturedArticles} from '@/components/eon/Editorial';
export default function Home(){return <main id="main"><DuctStory/>
<section id="spaces" className="section space-section"><div className="section-intro"><p className="eyebrow">01 / The spaces we share</p><h2>Care begins<br/>out of sight.</h2><div><p>Behind the ceiling. Beneath the fabric. Across the surfaces we touch every day.</p><p>EON brings AC cleaning, sanitisation and surface protection to homes and facilities in Abu Dhabi and across the UAE.</p><Link prefetch={false} href="/about-us/" className="text-link">Meet EON <span>↗</span></Link></div></div><figure className="wide-image"><img src="/images/A03-residential-room.webp" alt="Sunlit residential living room with a linear ceiling AC diffuser" width="1600" height="900" loading="lazy"/><figcaption>Residential spaces <span>Illustrative architectural scene</span></figcaption></figure></section>
<section className="section distinctions"><div className="section-intro"><p className="eyebrow">02 / Know the difference</p><h2>Different needs.<br/>Distinct services.</h2><p>The right approach starts with understanding the system and the surface. Cleaning, sanitisation and coating serve different purposes.</p></div><div className="process-columns"><article><span>01</span><h3>Duct cleaning</h3><p>Mechanical cleaning addresses settled dust and debris on internal surfaces. The cutaway above illustrates removal, not an EON service recording.</p></article><article><span>02</span><h3>AC sanitisation</h3><p>A separate service consideration alongside cleaning. Discuss the system, treatment and suitability with the EON team.</p></article><article><span>03</span><h3>Mold-resistant coating</h3><p>An optional protective coating for duct surfaces. It is not part of every cleaning job, and coating guidance does not describe how long a duct stays clean.</p><Link prefetch={false} href="/services/ac-duct-mold-resistant-coating/" className="text-link">Explore the coating <span>↗</span></Link></article></div></section>
<section className="section services-section"><div className="section-title"><div><p className="eyebrow">03 / What we do</p><h2>Air care. Surface care.<br/>A complete view.</h2></div><Link prefetch={false} href="/service/" className="text-link">All services <span>↗</span></Link></div><ServiceDirectory/></section>
<section className="section company-section"><img src="/images/A06-metal-handle.webp" alt="Brushed metal handle on a timber architectural door" width="900" height="1000" loading="lazy"/><div><p className="eyebrow">04 / The thinking behind the work</p><h2>Protection with<br/>a purpose.</h2><p>EON’s work spans residential, commercial, hospitality, healthcare, industrial and high-touch environments. Its focus is surface durability, hygiene and long-term performance.</p><p>Explore the company and its HealthGuard Protection Program information.</p><div className="company-links"><Link prefetch={false} href="/about-us/" className="text-link">About EON <span>↗</span></Link><Link prefetch={false} href="/hgpp-certification/" className="text-link">HGPP information <span>↗</span></Link></div></div></section>
<section className="section journal-section"><div className="section-title"><div><p className="eyebrow">05 / The journal</p><h2>A little more insight.</h2></div><Link prefetch={false} href="/media/" className="text-link">Browse the archive <span>↗</span></Link></div><FeaturedArticles/></section>
<section className="section faq-section"><div><p className="eyebrow">06 / Common questions</p><h2>Before you<br/>choose a coating.</h2><p>Guidance from EON’s coating information. Confirm the product and treatment conditions for your space.</p></div><Faqs/></section><Consultation/></main>}
