// Each illustrated answer owns one photograph. Nonvisual answers remain text-only.
// Shared questions use a shared key; branching questions include their area.
export const finderPhotos:Record<string,string>={
 '0|AC & ducts':'campaign/air.webp',
 '0|Furniture & fabric':'A07-woven-upholstery.webp',
 '0|Stone & shared surfaces':'campaign/stone.webp',
 '0|Exterior surfaces':'A11-stone-facade.webp',
 '1|Home or apartment':'A03-residential-room.webp',
 '1|Office or shop':'finder/office.webp',
 '1|Hotel or hospitality':'v2/V203-hospitality-lounge.webp',
 '1|Healthcare or shared facility':'finder/clinic.webp',
 'air|2|Central or ducted AC':'A12-ceiling-diffuser.webp',
 'air|2|Wall-mounted split units':'finder/split-ac.webp',
 'air|3|Dust or debris around vents':'A02-duct-interior.webp',
 'air|3|Visible patches or moisture':'finder/moisture.webp',
 'fabric|2|Sofa, chairs or upholstery':'campaign/fabric.webp',
 'fabric|2|Carpet or rugs':'A09-carpet-interior.webp',
 'fabric|2|Mattress':'A10-mattress-bedroom.webp',
 'fabric|3|An existing spill or stain':'finder/fabric-stain.webp',
 'fabric|3|Dust and general buildup':'finder/fabric-dust.webp',
 'fabric|3|Protection against future spills':'finder/fabric-protection.webp',
 'fabric|4|Natural or delicate textile':'finder/linen.webp',
 'fabric|4|Synthetic or blended fabric':'finder/synthetic.webp',
 'fabric|4|Leather or a coated finish':'finder/leather.webp',
 'fabric|4|Fitted carpet':'campaign/carpet.webp',
 'fabric|4|Loose rugs':'finder/rug.webp',
 'stone|2|Marble':'A08-marble-countertop.webp',
 'stone|2|Other natural stone':'campaign/marble.webp',
 'stone|2|Tile, laminate or a shared counter':'finder/tile.webp',
 'stone|3|Spill marks or staining':'finder/stone-spill.webp',
 'stone|3|Dullness or visible wear':'finder/wear.webp',
 'stone|3|Routine dirt or touch residue':'v2/V205-bronze-touchpoint.webp',
 'stone|3|Protection for a high-touch surface':'A06-metal-handle.webp',
 'stone|3|Protection against future spills':'v2/V202-stone-water-detail.webp',
 'stone|4|Kitchen or dining area':'finder/kitchen.webp',
 'stone|4|Bathroom or wet area':'finder/bathroom.webp',
 'stone|4|Living room or furniture':'v2/V201-residential-hero.webp',
 'stone|4|Reception or shared workspace':'A04-commercial-lounge.webp',
 'exterior|2|Stone or masonry':'finder/masonry.webp',
 'exterior|2|Concrete or render':'finder/concrete.webp',
 'exterior|2|Metal':'finder/metal.webp',
 'exterior|2|Glass or another finish':'finder/glass.webp',
 'exterior|3|Weathering or deterioration':'finder/weathering.webp',
 'exterior|3|Water marks or soiling':'finder/soiling.webp',
 'exterior|3|Dirt buildup':'finder/dirt.webp',
 'exterior|4|Strong direct sun':'campaign/exterior.webp',
 'exterior|4|Rain or frequent moisture':'finder/rain.webp',
 'exterior|4|Coastal exposure':'finder/coast.webp',
 'air|2|A mix of systems':'finder-v3/mixed-ac.webp',
 'air|3|An unusual or musty smell':'finder-v3/ac-odour.webp',
 'air|3|Routine cleaning':'finder-v3/routine-ac.webp',
 'air|3|Advice about protective duct coating':'finder-v3/duct-coating.webp',
 'air|4|Within the last year':'finder-v3/recent-service.webp',
 'air|4|More than a year ago':'finder-v3/older-service.webp',
 'air|4|Never, as far as I know':'finder-v3/never-service.webp',
 'fabric|3|An odour or hygiene concern':'finder-v3/fabric-odour.webp',
 'fabric|4|One mattress':'finder-v3/one-mattress.webp',
 'fabric|4|Two or three mattresses':'finder-v3/few-mattresses.webp',
 'fabric|4|Four or more mattresses':'finder-v3/many-mattresses.webp',
 'fabric|4|Both':'finder-v3/carpet-and-rug.webp',
 'exterior|3|Preventive protection':'finder-v3/exterior-protection.webp',
};
export function finderPhoto(option:string,area:string,step:number){
 const photo=finderPhotos[`${step<2?'':area+'|'}${step}|${option}`];
 return photo?'/images/'+photo:undefined;
}
