'use client';
import {useEffect,useRef,useState} from 'react';
import Link from '@/components/eon/PageLink';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {finderPhoto} from './finderPhotos';
import {services} from '@/lib/eon/services';
type Area='air'|'fabric'|'stone'|'exterior';
type Question={title:string;hint:string;options:string[]};
const areas:Area[]=['air','fabric','stone','exterior'];
const labels=['AC & ducts','Furniture & fabric','Stone & shared surfaces','Exterior surfaces'];
const property:Question={title:'What kind of space is it?',hint:'This helps EON understand access, usage and scheduling.',options:['Home or apartment','Office or shop','Hotel or hospitality','Healthcare or shared facility','Other / not sure']};
const questions:Record<Area,Question[]>={
 air:[{title:'What type of AC do you have?',hint:'Duct cleaning applies to systems with ductwork. It is fine if you do not know.',options:['Central or ducted AC','Wall-mounted split units','A mix of systems','Not sure']},{title:'What prompted you to look for AC care?',hint:'Visible signs guide the enquiry; they do not establish the cause.',options:['Dust or debris around vents','An unusual or musty smell','Visible patches or moisture','Routine cleaning','Advice about protective duct coating']},{title:'When were the ducts last professionally cleaned?',hint:'An approximate answer helps EON plan the assessment.',options:['Within the last year','More than a year ago','Never, as far as I know','I do not know']}],
 fabric:[{title:'What needs care?',hint:'Mattresses, carpets and upholstery have different service routes.',options:['Sofa, chairs or upholstery','Carpet or rugs','Mattress']},{title:'What would you like to address?',hint:'Cleaning existing marks and protecting against future spills are separate tasks.',options:['An existing spill or stain','Dust and general buildup','An odour or hygiene concern','Protection against future spills','Not sure which treatment fits']},{title:'What do you know about the material?',hint:'The fabric and its existing finish help determine how it can be treated.',options:['Natural or delicate textile','Synthetic or blended fabric','Leather or a coated finish','I do not know']}],
 stone:[{title:'Which material or surface is involved?',hint:'The material determines which coating may be suitable.',options:['Marble','Other natural stone','Tile, laminate or a shared counter','I do not know']},{title:'What needs attention?',hint:'Tell EON what you see or what you want to prevent.',options:['Spill marks or staining','Dullness or visible wear','Routine dirt or touch residue','Protection for a high-touch surface','Protection against future spills']},{title:'Where is the surface used?',hint:'Use and exposure matter when discussing preparation and care.',options:['Kitchen or dining area','Bathroom or wet area','Living room or furniture','Reception or shared workspace','Other area']}],
 exterior:[{title:'What is the exterior material?',hint:'The surface material helps determine which coating can be used.',options:['Stone or masonry','Concrete or render','Metal','Glass or another finish','Not sure']},{title:'What is the main concern?',hint:'An enquiry does not assume that coating will repair existing damage.',options:['Weathering or deterioration','Water marks or soiling','Dirt buildup','Preventive protection']},{title:'What exposure does it face?',hint:'This helps frame the discussion about an appropriate product.',options:['Strong direct sun','Rain or frequent moisture','Coastal exposure','Mixed exposure / not sure']}]
};
const KEY='eon-finder-v2';
export default function FinderModal(){const [open,setOpen]=useState(false),[step,setStep]=useState(0),[answers,setAnswers]=useState<string[]>([]);const trigger=useRef<HTMLElement|null>(null);const heading=useRef<HTMLHeadingElement>(null);const panel=useRef<HTMLDivElement>(null);const lastChoice=useRef(0);
useEffect(()=>{try{sessionStorage.removeItem(KEY)}catch{}
 const startFresh=()=>{lastChoice.current=0;setAnswers([]);setStep(0);setOpen(true)};
 const launch=(e:Event)=>{if(e instanceof MouseEvent&&(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||e.button!==0))return;const a=e.target instanceof Element?e.target.closest('a'):null;if(a&&new URL(a.href).pathname.replace(/\/$/,'')==='/service-finder'){e.preventDefault();trigger.current=a;startFresh()}};
 const custom=()=>{trigger.current=document.activeElement as HTMLElement;startFresh()};document.addEventListener('click',launch,true);window.addEventListener('eon:finder',custom);if(new URLSearchParams(location.search).get('finder')==='open'){startFresh();const url=new URL(location.href);url.searchParams.delete('finder');history.replaceState(history.state,'',url)}return()=>{document.removeEventListener('click',launch,true);window.removeEventListener('eon:finder',custom)}},[]);
useEffect(()=>{if(open){heading.current?.focus();panel.current?.scrollTo({top:0})}},[step,open]);
const area=areas[labels.indexOf(answers[0])]||'air';
const sequence:Question[]=[{title:'What needs attention?',hint:'Choose one area to begin. You can review another afterwards.',options:labels},property,...questions[area]];
if(area==='fabric'&&answers[2]==='Mattress')sequence[4]={title:'How many mattresses need care?',hint:'This helps EON understand the size of the enquiry.',options:['One mattress','Two or three mattresses','Four or more mattresses','Not sure yet']};
if(area==='fabric'&&answers[2]==='Carpet or rugs')sequence[4]={title:'Is it fitted carpet or loose rugs?',hint:'The type of carpet and where it is fitted affect how it can be cleaned.',options:['Fitted carpet','Loose rugs','Both','Not sure']};
if(area==='air'&&answers[2]==='Wall-mounted split units')sequence[4]={...sequence[4],title:'When were the AC units last professionally serviced?',hint:'EON can confirm the applicable service for a system without ducts.'};
if(area==='air'&&answers[2]==='Wall-mounted split units')sequence[3]={...sequence[3],options:sequence[3].options.filter(o=>o!=='Advice about protective duct coating')};
const q=sequence[step];
const idx=area==='air'?0:area==='fabric'?(answers[2]==='Mattress'?5:answers[3]==='Protection against future spills'&&answers[2]!=='Carpet or rugs'?2:4):area==='stone'?(answers[2]==='Marble'||answers[2]==='Other natural stone'?3:1):6;
const service=services[idx];
const rationale=area==='air'?(answers[2]==='Wall-mounted split units'?'You selected wall-mounted split units. These may not have ductwork. Ask EON to confirm the system and the work needed before arranging duct cleaning.':answers[3]==='Advice about protective duct coating'?'You asked about internal protection. Mold-resistant coating is separate from cleaning and sanitisation; EON needs to assess preparation and product suitability.':answers[3]==='Routine cleaning'?'You selected routine cleaning. Share the areas served by your AC and when it was last cleaned so EON can confirm the work needed.':'Share the symptoms and where you notice them so EON can assess your AC system. Cleaning, sanitisation and coating are separate services; the right choice depends on what is found.'):area==='fabric'?(idx===5?'Your selection points to EON’s dedicated mattress cleaning and sanitisation service.':idx===2?'You want protection against future spills on upholstery. Stain-resistant coating is the relevant service to discuss after material suitability is confirmed.':'Your selection points to carpet and furniture deep cleaning. Tell EON about any stain, odour and the fabric or finish before treatment.'):area==='stone'?(idx===3?'You selected natural stone. Discuss marble protective coatings and the existing condition with EON. Coating is not a promise to restore dullness or remove damage.':'For shared surfaces, discuss anti-microbial surface coating and suitable cleaning or preparation. EON needs to confirm the actual material and product.'): 'Your material and exposure details give EON a starting point for discussing specialty coatings. Existing damage and preparation need assessment.';
const summary='Appointment request: '+service.title+'\n\n'+answers.map((v,i)=>`${sequence[i].title}\n${v}`).join('\n\n');const goal=idx===2||idx===3||idx===6?'protect':'clean';const context=`from=finder&area=${area}&goal=${goal}`;
return <Dialog open={open} onOpenChange={setOpen}><DialogContent ref={panel} className="finder-modal" onCloseAutoFocus={e=>{e.preventDefault();trigger.current?.focus({preventScroll:true})}}><DialogTitle className="sr-only">Find your EON service</DialogTitle><DialogDescription className="sr-only">A tailored five-question guide. Each new visit starts fresh. Complete the guide to include your answers in an enquiry.</DialogDescription><div className="finder-progress"><span>{step<5?`Question ${step+1} of 5`:'Your recommendation'}</span><span>Service finder</span></div><div className="finder-progress-bar"><span style={{width:`${Math.min(100,step*20)}%`}}/></div>
{step<5?<div className="finder-question" key={`${step}-${area}`}><h2 ref={heading} tabIndex={-1}>{q.title}</h2><p className="finder-hint">{q.hint}</p><div className="question-options" role="group" aria-label={q.title}>{q.options.map(option=><button key={option} className={finderPhoto(option,area,step)?'has-photo':'text-option'} aria-pressed={answers[step]===option} onClick={()=>{const now=Date.now();if(now-lastChoice.current<350)return;lastChoice.current=now;setAnswers(a=>step===0&&a[0]!==option?[option]:[...a.slice(0,step),option,...(step===2&&a[step]!==option?[]:a.slice(step+1))]);setStep(step+1)}}>{finderPhoto(option,area,step)&&<img src={finderPhoto(option,area,step)} alt="" width="180" height="130"/>}<span>{option}</span><i className="option-radio" aria-hidden="true"/></button>)}</div><div className="finder-controls"><button disabled={step===0} onClick={()=>setStep(step-1)}>← Previous</button><span className="finder-auto-hint">Select an answer to continue</span></div></div>:<><h2 ref={heading} tabIndex={-1}>{idx===0?'AC cleaning: your next step':service.title}</h2><p className="finder-hint">{rationale}</p><section className="finder-answer-summary" aria-label="Your five answers"><h3>Your five answers</h3>{answers.map((a,i)=><div key={i}><span>{sequence[i].title}</span><strong>{a}</strong><button onClick={()=>setStep(i)}>Edit</button></div>)}</section><Link className="button" href={`/contact-us/?service=${service.slug}&${context}&type=${answers[1]==='Home or apartment'?'Residential':'Business'}&enquiry=${encodeURIComponent(summary)}`} onClick={()=>setOpen(false)}>Request an appointment</Link><Link className="finder-learn" href={`/services/${service.slug}/?${context}`} onClick={()=>setOpen(false)}>Read about the service ›</Link><button className="finder-reset" onClick={()=>{setAnswers([]);setStep(0)}}>Explore a different area</button><p className="finder-privacy">Your answers help EON understand the job. They do not confirm a diagnosis or booking.</p></>}
</DialogContent></Dialog>}
