import FinderButton from './FinderButton';
import SpacesGallery from './SpacesGallery';
import Link from '@/components/eon/PageLink';
import {HGPPCertificate} from '@/components/eon/CompanyPages';
export default function HomeCare(){
 return <div className="care-editorial">
  <section id="why-eon" className="care-section care-reasons" aria-labelledby="care-reasons-title"><div className="care-range-heading"><div><p className="eyebrow">What sets us apart</p><h2 id="care-reasons-title">Why choose us?</h2></div><p>Professional care, from choosing the treatment to looking after your space afterwards.</p></div><div className="care-reasons-grid">{[
   ['Certified and tested coatings','Coatings selected for the surface and the job, with product testing and certification explained before treatment.'],
   ['Professional service teams','Specialist teams for AC care, deep cleaning and protective coating application.'],
   ['Care for people and pets','Confirm product suitability, preparation and when children and pets can return to the treated space.'],
   ['After-sales support','Practical guidance on caring for treated surfaces, with support after the work is complete.']
  ].map(([title,copy],i)=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="care-proof"><div className="care-proof-inner"><div className="care-proof-copy"><p className="eyebrow">Our difference</p><span className="care-hgpp-word">HGPP</span><h2>Certification for<br/>treated premises.</h2><p>The HealthGuard Protection Program gives qualifying treated premises a conformity certificate to display.</p><p>Certification records the qualifying treatment and premises. We explain the coverage, validity and maintenance requirements.</p><Link href="/hgpp-certification/" className="button">Explore HGPP certification <span aria-hidden="true">›</span></Link></div><HGPPCertificate/></div></section>
  <section className="care-section care-spaces" id="spaces-we-care-for" aria-labelledby="home-spaces-title"><div className="care-range-heading"><div><p className="eyebrow">Villas, homes &amp; commercial properties</p><h2 id="home-spaces-title">Properties we service.</h2></div><p>Care for your villa, from AC systems to furniture and stone surfaces.</p></div><SpacesGallery/></section>
  <section className="care-section care-next"><div><p className="eyebrow">Service enquiries</p><h2>Find the service<br/>you need.</h2><p>Start with a few simple questions about your space. We’ll help you find the relevant services.</p><FinderButton/><Link href="/contact-us/" className="care-secondary">Already know what you need? Contact us</Link></div><div className="care-next-details"><ol><li><span>01</span><div><h3>Choose a service</h3><p>Tell us about the system, material or room.</p></div></li><li><span>02</span><div><h3>Talk through the details</h3><p>Share its condition, your location and what you want to address.</p></div></li><li><span>03</span><div><h3>Plan the work</h3><p>Confirm the service, timing and aftercare with us.</p></div></li></ol><details><summary>Cleaning or coating?</summary><p>Cleaning removes accumulated dirt. Sanitisation and protective coatings have different purposes. The right approach depends on the material and its condition.</p></details><details><summary>More than one service?</summary><p>Yes. Share everything that needs attention so we can discuss the requirements together.</p></details></div></section>
 </div>
}
