'use client';
import Link from '@/components/eon/PageLink';
import { useState } from 'react';
import {cleanText,dateLabel,recordPath} from '@/lib/eon/public-format';
import type {ContentRecord} from '@/lib/eon/content-types';
export default function MediaIndex({articles,initialQuery="",initialCategory="All",initialLimit=9}:{articles:Pick<ContentRecord,'id'|'title'|'date'|'url'|'categories'|'contentText'|'featuredMedia'>[];initialQuery?:string;initialCategory?:string;initialLimit?:number}){
 const [query,setQuery]=useState(initialQuery),[category,setCategory]=useState(initialCategory),[limit,setLimit]=useState(initialLimit);
 const cats=['All',...Array.from(new Set(articles.flatMap(a=>a.categories.map(c=>c.name))))];
 function change(q:string,c:string,n=9){setQuery(q);setCategory(c);setLimit(n);const params=new URLSearchParams();if(q)params.set('q',q);if(c!=='All')params.set('category',c);if(n!==9)params.set('limit',String(n));history.replaceState(null,'',`/media/${params.size?'?'+params:''}`);}
 const found=articles.filter(a=>(category==='All'||a.categories.some(c=>c.name===category))&&(a.title+' '+a.contentText).toLowerCase().includes(query.toLowerCase()));
 return <section className="section media-results"><div className="archive-tools"><label>Search media<input type="search" value={query} onChange={e=>change(e.target.value,category)} placeholder="Search by topic"/></label><div className="filter-buttons" aria-label="Article categories">{cats.map(c=><button key={c} aria-pressed={category===c} onClick={()=>change(query,c)}>{c}</button>)}</div></div><p className="result-count" role="status">{found.length} {found.length===1?'article':'articles'}</p><div className="article-grid">{found.slice(0,limit).map((a,i)=><Link prefetch={false} className="article-card" key={a.id} href={recordPath(a)}><img src={a.featuredMedia?.url||`/images/${i%2?'A03-residential-room.webp':'A12-ceiling-diffuser.webp'}`} alt={a.featuredMedia?.alt||'Architectural ventilation detail'} width="800" height="540" loading="lazy"/><p className="eyebrow">{dateLabel(a.date)} / {a.categories.map(c=>c.name).join(', ')} · {Math.max(1,Math.ceil(a.contentText.split(/\s+/).length/200))} min read</p><h2>{cleanText(a.title)}</h2><span className="text-link">Read article <span>›</span></span></Link>)}</div>{found.length===0&&<div className="empty-results"><h2>No articles found.</h2><p>Try a different topic or choose All.</p><button onClick={()=>change('','All')} className="button">Reset search</button></div>}{found.length>limit&&<button className="button load-more" onClick={()=>change(query,category,limit+9)}>Load more articles</button>}</section>;
}
