import Link from 'next/link';
import {ArrowUpRight} from 'lucide-react';
import {services} from '@/lib/eon/content';
import {Consultation,PageHeading} from './Editorial';
const settings:Record<string,{title:string;headline:string;image:string;copy:string;serviceIds:number[]}>= {
 offices:{title:'Offices',headline:'Care for the places you work.',image:'A04-commercial-lounge.webp',copy:'From shared touchpoints to meeting-room upholstery and AC systems, explore cleaning and protection for the materials in your workplace.',serviceIds:[1,2,4,0]},
 healthcare:{title:'Healthcare',headline:'A considered approach to shared surfaces.',image:'v2/V205-bronze-touchpoint.webp',copy:'Discuss anti-microbial surface coating, interior cleaning and AC care for high-touch settings. Product suitability and facility requirements should guide the service conversation.',serviceIds:[1,4,0]},
 education:{title:'Education',headline:'Spaces for learning. Surfaces for everyday life.',image:'A06-metal-handle.webp',copy:'Doors, shared furniture and interior surfaces are part of the daily life of a learning environment. Explore relevant care options and discuss your facility’s requirements.',serviceIds:[1,2,4,0]},
 hospitality:{title:'Hospitality',headline:'Look after every part of the welcome.',image:'v2/V203-hospitality-lounge.webp',copy:'Lobby seating, marble counters, guest-room mattresses and the air systems behind the ceiling. Find relevant services for the spaces your guests use.',serviceIds:[2,3,5,0]}
};
export default function SectorPage({slug,source}:{slug:string;source:string}){const s=settings[slug];return <main id="main"><PageHeading label={`Spaces / ${s.title}`} title={s.headline} description={s.copy}/><figure className="sector-image"><img src={`/images/${services[s.serviceIds[0]].image}`} alt={`Illustrative ${s.title.toLowerCase()} surface-care context`} width="1500" height="900"/><figcaption>Illustrative setting, not a documented EON project.</figcaption></figure><section className="section"><div className="section-title"><div><p className="eyebrow">Relevant care options</p><h2>Start with<br/><em>your surfaces.</em></h2></div><Link prefetch={false} href="/contact-us/" className="text-link">Discuss your facility <ArrowUpRight size={18}/></Link></div><div className="visual-services">{s.serviceIds.map(i=>{const v=services[i];return <Link prefetch={false} className="visual-service" key={v.slug} href={`/services/${v.slug}/`}><div className="service-photo"><img src={`/images/${v.image}`} alt={`Illustrative ${v.label.toLowerCase()}`} width="650" height="800" loading="lazy"/><span className="round-arrow"><ArrowUpRight size={20}/></span></div><h3>{v.title}</h3><p>{v.short}</p></Link>})}</div></section><section className="section sector-source"><details className="source-disclosure"><summary>Existing company information for this sector</summary><p className="source-note">EON’s original sector information follows. Some pages reuse hospitality wording and numerical claims. Confirm the applicable product evidence and conditions for your setting.</p><div className="prose" dangerouslySetInnerHTML={{__html:source}}/></details></section><Consultation/></main>}
