import {SectorBenefits} from './RestoredSections';
import {sectorPhotos} from '@/lib/eon/photo-placements';
import Link from '@/components/eon/PageLink';
import {services} from '@/lib/eon/services';
import {CompanyHero,spaces} from './CompanyPages';
const planning:Record<string,[string,string][]>= {
 offices:[['Around working hours','Share office hours, meeting-room availability and any areas that must remain in use.'],['Access to the building','Mention visitor registration, loading access and permissions for ceiling or plant areas.'],['One clear enquiry','List the AC systems, seating and shared surfaces together so each service can be considered in the quote.']],
 healthcare:[['Facility procedures','Share the facility’s cleaning requirements and contractor access procedures before selecting a treatment.'],['Materials and products','Identify the surfaces involved and any restrictions on cleaning products or coatings.'],['Occupied areas','Explain which rooms remain in use and who coordinates access. Treatment must fit the facility’s operating requirements.']],
 education:[['Outside teaching time','Share term dates and the periods when classrooms and shared spaces are available.'],['Daily contact points','List desks, handles, shared seating and other frequently used surfaces alongside AC requirements.'],['Reopening the space','Confirm preparation and when treated surfaces or cleaned furnishings can be used again.']],
 hospitality:[['Room availability','Group the rooms or floors involved and identify the available service windows.'],['Guest-facing materials','Describe upholstery, mattress types and stone finishes so the treatment can be matched to the material.'],['Ready for the next guest','Ask about drying, room access and the maintenance instructions needed by housekeeping.']]
};
export default function SectorPage({slug}:{slug:string;source:string}){const s=spaces.find(x=>x.slug===slug)!;return <main id="main" className="company-page"><CompanyHero label={s.title} title={`Cleaning and protection for ${slug==='education'?'learning environments':slug==='healthcare'?'healthcare facilities':slug==='hospitality'?'guest spaces':'offices'}.`} copy={s.copy} image={`unique-care/${sectorPhotos[slug].hero}.webp`}><Link className="button" href="/service-finder/">Find my service <span>›</span></Link></CompanyHero><section className="section sector-care"><div className="section-title"><h2>Services for {s.title.toLowerCase()}.</h2><Link className="text-link" href="/service/">Back to services <span>›</span></Link></div><ul className="sector-needs compact-needs">{s.needs.map(n=><li key={n}>{n}</li>)}</ul><div className="sector-service-grid">{s.ids.map(i=>{const v=services[i];const photo=sectorPhotos[slug].services[i];return <Link key={v.slug} href={`/services/${v.slug}/`}><img src={`/images/unique-care/${photo.image}.webp`} alt={photo.alt+'; illustrative photograph'} width="768" height="512" loading="lazy"/><div><h3>{v.title}</h3><p>{photo.copy}</p><span>View service ›</span></div></Link>})}</div></section><SectorBenefits slug={slug}/><section className="section service-guide sector-planning"><div className="section-title"><h2>Planning your visit.</h2><p>Include these details when you enquire so EON can understand the work and access required.</p></div><div className="service-guide-grid">{planning[slug].map(([title,copy],i)=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="section company-next"><div><p className="eyebrow">HGPP certification</p><h2>Make surface protection visible.</h2><p>Explore antimicrobial treatment and certification for qualifying premises through the HealthGuard Protection Program.</p></div><Link className="button" href="/hgpp-certification/">View HGPP certification</Link></section></main>}
