import {CoatingTechnology} from './RestoredSections';
import Link from '@/components/eon/PageLink';
import {services} from '@/lib/eon/content';
import {serviceStories} from '@/lib/eon/service-stories';
import {serviceGuides} from '@/lib/eon/service-guides';
import JourneyNav,{ServiceEnquiry} from './JourneyNav';
export default function ServiceDetail({slug}:{slug:string;sourceHtml:string}){
 const service=services.find(s=>s.slug===slug)!;const story=serviceStories[slug];const guide=serviceGuides[slug];const air=slug==='ac-duct-mold-resistant-coating';
 return <main id="main"><JourneyNav current={service.title}/><section className="service-hero-new"><div><p className="eyebrow">{service.label}</p><h1>{service.title}</h1><p>{guide.intro}</p><div className="service-actions"><Link href="/service-finder/" className="button">Find my service <span>›</span></Link><ServiceEnquiry slug={slug} title={service.title}/></div></div><figure><img src={`/images/${service.image}`} width="1536" height="1024" alt={air?'Ceiling air grille in a residential interior':service.title+' illustrative photograph'}/></figure></section>
 <section className="section service-guide"><div className="section-title"><div><p className="eyebrow">{air?'Three different services':'Before you choose'}</p><h2>{air?'Cleaning, sanitisation and coating.':'The right treatment starts here.'}</h2></div><p>{air?'Choose the work your system needs. Additional treatments should be confirmed separately.':story.detail}</p></div><div className="service-guide-grid">{guide.steps.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
 <section className="section service-scenario"><img src={`/images/${story.sceneImage}`} width="1000" height="700" alt={story.scenario+' illustrative photograph'} loading="lazy"/><div><p className="eyebrow">Where this service helps</p><h2>{air?'Beyond the visible grille.':story.sceneTitle}</h2><p>{story.sceneCopy}</p><ul>{story.uses.map(u=><li key={u}>{u.replace(' enquiries','')}</li>)}</ul></div></section>
 <CoatingTechnology slug={slug}/><section className="section service-faq"><div><p className="eyebrow">Plan your visit</p><h2>Questions before you book.</h2><p>Clear information helps you choose the right work and prepare for the visit.</p></div><div className="faq-list">{guide.questions.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
 <section className="section service-next"><div><h2>Ready to take the next step?</h2><p>Use the service finder for guidance, or ask EON about {air?'AC duct cleaning':service.title.toLowerCase()}.</p></div><div className="service-actions"><Link className="button" href="/service-finder/">Find my service <span>›</span></Link><ServiceEnquiry slug={slug} title={service.title}/></div></section></main>
}
