'use client';
import SiteSearch from './SiteSearch';
import {ThemeToggle} from './ThemeControls';
import Link from '@/components/eon/PageLink';
import {useState} from 'react';
import {usePathname} from 'next/navigation';
import { Menu, ChevronRight, ChevronDown, ShieldCheck } from 'lucide-react';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const mainLinks=[['Home','/'],['Services','/service/'],['Industries','/industry/'],['HGPP Certification','/hgpp-certification/']];
const companyLinks=[['About Eon Coatings','/about-us/'],['Contact','/contact-us/']];
const mobileLinks=[...mainLinks,...companyLinks];
const links=[['Find my service','/service-finder/'],...mobileLinks,['Media','/media/'],['Client stories','/success-stories-client-results/']];
function isCurrent(path:string,href:string){const current=path.replace(/\/$/,'');const target=href.replace(/\/$/,'');return current===target||(target==='/service'&&(current==='/services'||current.startsWith('/services/')))||(target==='/industry'&&(current==='/industries'||current.startsWith('/industries/')));}
export function Header(){const pathname=usePathname();const [open,setOpen]=useState(false);return <><Link prefetch={false} className="skip-link" href="#main">Skip to content</Link><header className="site-header"><Link prefetch={false} href="/" aria-label="Eon Coatings home"><img src="/images/eon-logo.png" alt="Eon Coatings" width="130" height="60"/></Link><nav className="desktop-nav" aria-label="Main navigation">{mainLinks.map(([label,href])=><Link prefetch={false} href={href} key={href} className={href==='/hgpp-certification/'?'nav-hgpp':undefined} aria-current={isCurrent(pathname,href)?'page':undefined}>{href==='/hgpp-certification/'&&<ShieldCheck size={17} aria-hidden="true"/>}{label}</Link>)}<DropdownMenu><DropdownMenuTrigger className="company-menu-trigger" data-current={companyLinks.some(([,href])=>isCurrent(pathname,href))||undefined}>Company <ChevronDown size={15} aria-hidden="true"/></DropdownMenuTrigger><DropdownMenuContent align="end" sideOffset={14} className="company-menu-content">{companyLinks.map(([label,href])=><DropdownMenuItem asChild key={href}><Link prefetch={false} href={href} aria-current={isCurrent(pathname,href)?'page':undefined}>{label}</Link></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></nav><div className="header-right"><ThemeToggle/><SiteSearch/><Link prefetch={false} href="/service-finder/" className="button header-cta">Find my service <ChevronRight size={16}/></Link><Dialog open={open} onOpenChange={setOpen}><DialogTrigger className="menu-trigger" aria-label="Open navigation menu">Menu <Menu size={22}/></DialogTrigger><DialogContent className="eon-menu"><DialogTitle className="eyebrow">Explore Eon Coatings</DialogTitle><DialogDescription className="sr-only">Services, company information and contact details.</DialogDescription><nav aria-label="Mobile navigation">{mobileLinks.map(([label,href],i)=><Link prefetch={false} href={href} key={href} className={href==='/hgpp-certification/'?'nav-hgpp':undefined} aria-current={isCurrent(pathname,href)?'page':undefined} onClick={()=>setOpen(false)}><span>{href==='/hgpp-certification/'?<ShieldCheck size={21} aria-hidden="true"/>:`0${i+1}`}</span>{label}<ChevronRight/></Link>)}</nav><Link prefetch={false} href="/service-finder/" className="button" onClick={()=>setOpen(false)}>Find my service <ChevronRight size={18}/></Link><p>M17, Mussafah<br/>Abu Dhabi, UAE</p><Link prefetch={false} href="mailto:info@eoncoatings.com">info@eoncoatings.com</Link></DialogContent></Dialog></div></header></>;}
export function Footer(){return <footer><div className="footer-top"><Link prefetch={false} href="/" aria-label="Eon Coatings home"><img src="/images/eon-logo.png" alt="Eon Coatings" width="130" height="60"/></Link><Link prefetch={false} href="/contact-us/" className="text-link">Let’s talk <ChevronRight/></Link></div><div className="footer-grid"><div><p className="eyebrow">Visit</p><p>M17, Mussafah<br/>Abu Dhabi, UAE</p><p>Monday to Saturday<br/>9:00 AM to 5:00 PM<br/>Sunday closed</p></div><div><p className="eyebrow">Contact</p><Link prefetch={false} href="tel:+97125639468">+971 (02) 563 9468</Link><Link prefetch={false} href="mailto:info@eoncoatings.com">info@eoncoatings.com</Link></div><nav aria-label="Footer">{links.map(([label,href])=><Link prefetch={false} href={href} key={href}>{label}</Link>)}</nav><nav aria-label="Social"><Link prefetch={false} href="https://www.linkedin.com/company/eon-coatings/">LinkedIn</Link><Link prefetch={false} href="https://www.instagram.com/eoncoatings/">Instagram</Link><Link prefetch={false} href="https://www.facebook.com/share/1DGkKVpxqV/?mibextid=wwXIfr">Facebook</Link></nav></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Eon Coatings</span><Link prefetch={false} href="/privacy-policy/">Privacy policy</Link><Link prefetch={false} href="/terms-and-conditions/">Terms &amp; conditions</Link><span>Abu Dhabi, UAE</span></div></footer>;}
