'use client';
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {ArrowUpRight,ArrowRight} from 'lucide-react';
import {services} from '@/lib/eon/content';
const catalogue=[...services.slice(1,4),services[6],services[4],services[5],{...services[0],title:'AC cleaning & sanitisation',short:'Care for the air systems that serve your space.',label:'Indoor air',slug:'ac-duct-mold-resistant-coating#cleaning'},services[0]];
const scenarioData=[
 {name:'At home',image:'v2/V201-residential-hero.webp',title:'Live in it. Love it. Look after it.',copy:'A sofa for slow mornings. A kitchen made for cooking. A bedroom to retreat to. Find the care that fits the way you live.',links:[['Sofas & upholstery',2],['Marble counters & floors',3],['Carpets & furniture',4],['Mattresses',5]] as [string,number][]},
 {name:'At work',image:'A04-commercial-lounge.webp',title:'A space ready for every working day.',copy:'Meeting rooms, shared touchpoints and busy communal spaces each need a considered approach to cleaning and protection.',links:[['Shared touchpoints',1],['Meeting-room furniture',2],['Carpets & soft furnishings',4],['AC systems',0]] as [string,number][]},
 {name:'Hospitality',image:'v2/V203-hospitality-lounge.webp',title:'Make every welcome feel considered.',copy:'From lobby seating to guest bedrooms, care for the materials and surfaces that shape a guest’s experience.',links:[['Guest-room mattresses',5],['Lobby seating',2],['Stone reception counters',3],['Exterior finishes',6]] as [string,number][]},
 {name:'Shared spaces',image:'v2/V205-bronze-touchpoint.webp',title:'Care for the surfaces we all share.',copy:'In healthcare, education and other high-touch environments, discuss surface compatibility and product requirements with EON.',links:[['High-touch surfaces',1],['Interior furniture',4],['Air-system coatings',0],['Specialty finishes',6]] as [string,number][]}
];
export function SurfaceExplorer(){const [filter,setFilter]=useState('All services');useEffect(()=>{const sync=()=>{if(location.hash==='#protection')setFilter('Protect surfaces');if(location.hash==='#cleaning')setFilter('Clean & refresh');};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync);},[]);const visible=catalogue.filter(s=>filter==='All services'||(filter==='Protect surfaces'?!s.title.includes('cleaning'):s.title.includes('cleaning')));return <><div className="service-filters" aria-label="Filter services">{['All services','Protect surfaces','Clean & refresh'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}{filter===f&&<span aria-hidden="true">↗</span>}</button>)}</div><div className="visual-services" aria-live="polite">{visible.map((s)=><Link prefetch={false} href={`/services/${s.slug}/`.replace('#cleaning/','#cleaning')} className="visual-service" key={s.title}><div className="service-photo"><img src={`/images/${s.image}`} srcSet={`/images/responsive/${s.image.split('/').pop()?.replace('.webp','')}-480.webp 480w, /images/responsive/${s.image.split('/').pop()?.replace('.webp','')}-800.webp 800w`} sizes="(max-width:550px) 44vw, (max-width:800px) 44vw, (max-width:1100px) 28vw, 23vw" alt={s.label+' setting, illustrative image'} width="650" height="800" loading="lazy"/><span className="service-tag">{s.label}</span><span className="round-arrow"><ArrowUpRight size={22}/></span></div><h3>{s.title}</h3><p>{s.short}</p></Link>)}</div></>}
export function Scenarios(){const [selected,setSelected]=useState(0);const s=scenarioData[selected];return <section className="scenarios section" id="your-space"><div className="section-title"><div><p className="eyebrow">A place for every kind of care</p><h2>What does your<br/><em>space need?</em></h2></div><p>Start with where you are.<br/>We’ll help you find the right service.</p></div><div className="scenario-tabs" role="group" aria-label="Choose your setting">{scenarioData.map((x,i)=><button aria-pressed={selected===i} onClick={()=>setSelected(i)} key={x.name}><span aria-hidden="true">0{i+1}</span>{x.name}<ArrowUpRight size={18}/></button>)}</div><div className="scenario-body" key={s.name}><figure><img src={`/images/${s.image}`} alt={`Illustrative ${s.name.toLowerCase()} setting`} width="1400" height="1000" loading="lazy"/><figcaption>Spaces shown are illustrative, not EON project photographs.</figcaption></figure><div className="scenario-detail"><p className="eyebrow">{s.name} / EON care</p><h3>{s.title}</h3><p>{s.copy}</p><nav aria-label={`${s.name} services`}>{s.links.map(([title,i])=><Link prefetch={false} key={title} href={`/services/${services[i].slug}/`}>{title}<ArrowRight size={19}/></Link>)}</nav><Link prefetch={false} className="text-link" href="/contact-us/">Talk through your requirements <ArrowUpRight size={18}/></Link></div></div></section>}
